panel_hesap_homepage:
  path:     /
  defaults: { _controller: PanelBundle:Hesap:index }

panel_hesap_bilgileriKaydet:
  path:     /bilgileriKaydet
  defaults: { _controller: PanelBundle:Hesap:bilgileriKaydet }

panel_hesap_sifreDegistir:
  path:     /sifreDegistir
  defaults: { _controller: PanelBundle:Hesap:sifreDegistir }
