panel_homepage:
    path:     /
    defaults: { _controller: PanelBundle:Default:index }

panel_ofis:
    resource: "@PanelBundle/Resources/config/ofis.yml"
    prefix:   /ofis/

panel_hesap:
    resource: "@PanelBundle/Resources/config/hesap.yml"
    prefix:   /hesap/

panel_hesaplar:
    resource: "@PanelBundle/Resources/config/hesaplar.yml"
    prefix:   /hesaplar/

panel_aracgrup:
    resource: "@PanelBundle/Resources/config/aracgrup.yml"
    prefix:   /arac_grup/

panel_arac:
    resource: "@PanelBundle/Resources/config/arac.yml"
    prefix:   /arac/
