
# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

panel:
    resource: "@PanelBundle/Resources/config/routing.yml"
    prefix:   /panel/

site:
    resource: "@SiteBundle/Resources/config/routing.yml"
    prefix:   /